M48
; DRILL file {KiCad 8.0.0} date 2024-02-29T11:48:53+0100
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2024-02-29T11:48:53+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,8.0.0
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0256
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.0669
%
G90
G05
T1
X1.0866Y-1.8547
X1.0866Y-2.0823
T2
X1.9882Y-1.9685
X2.2638Y-1.9685
M30
